#
# Hardware settings for Lenovo Thinkpad T15 Gen1 15.6" Laptop
# Dual boot active. Windows @ sda2 / NixOS @ sda4
#
# flake.nix
#  └─ ./hosts
#      └─ ./r510jx
#          ├─ default.nix
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, modulesPath, host, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4cb4acdd-9ba3-4bf1-81f8-abfc3752f285";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2EF5-EDD6";
      fsType = "vfat";
    };

  # fileSystems."/windows" =
  #   { device = "/dev/disk/by-uuid/76a25d6aa25d2fbb";
  #     fsType = "ntfs";
  #     options = [ "nofail" "uid=1000" "gid=100" ];
  #   };

  swapDevices = [ ];

  networking = with host; {
    useDHCP = lib.mkDefault true;
    hostName = hostName;
    enableIPv6 = false;
    networkmanager.enable = true;
    networkmanager.wifi.scanRandMacAddress = false;
    firewall = {
      # if packets are still dropped, they will show up in dmesg
      logReversePathDrops = true;
      # wireguard trips rpfilter up
      extraCommands = ''
        ip46tables -t mangle -I nixos-fw-rpfilter -p udp -m udp --sport 51820 -j RETURN
        ip46tables -t mangle -I nixos-fw-rpfilter -p udp -m udp --dport 51820 -j RETURN
      '';
      extraStopCommands = ''
        ip46tables -t mangle -D nixos-fw-rpfilter -p udp -m udp --sport 51820 -j RETURN || true
        ip46tables -t mangle -D nixos-fw-rpfilter -p udp -m udp --dport 51820 -j RETURN || true
      '';
    }; # To load wireguard cert in nm-applet: nmcli connection import type wireguard file <config file>
    bridges = {
      "br0" = {
        # Replace `enp*` with output from `ip link show`
        interfaces = [ "enp4s0f1" ];
      };
    };
    interfaces = {
      #enp0s31f6.useDHCP = lib.mkDefault true;
      #wlp0s20f3.useDHCP = lib.mkDefault true;
      br0.useDHCP = true;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
